### ISSUE TITLE
docker: Error response from daemon: repository not found

### ISSUE THREAD

**Issue by nhodges** [bergerx/docker-mysql-replication#2]
If I turn off host machine, or manually stop the docker containers, when I re-launch them I run into this error:

```
docker: Error response from daemon: repository de8a92bf181b not found: does not exist or no pull access.
```

**Comment by tleveque-ellevest** [comment]
You should use `bergerx/mysql-replication:5.7` instead of `bergerx/mysql_slavetion:5.7`

**Comment by bergerx** [comment]
Wow, just saw this old issue, I guess it was not related to the repo.

Actually, this was an old proof of project that has never been used for production, I'm not sure it's even safe to use this for any purpose. I never thought I'd have issues created against this repo :)
